name: example
description: A pro_validator example app.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  pro_validator:
    path: ../

dev_dependencies:
  pro_lints: ^5.0.0

flutter:
  uses-material-design: true
