name: validator
description: The validator package comes with several common validations and removes the boiler plate code from your project.
version: 1.0.0+3
homepage: https://github.com/pro100andrey/validator

environment:
  sdk: '>=2.18.1 <3.0.0'

dev_dependencies:
  test: ^1.21.6
